name: Renovate

on:
  schedule:
    - cron: "11,22,33,44,55 */6 * * *"
  workflow_dispatch:

concurrency:
  group: renovate
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: renovatebot/github-action@v46.3.7
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
